apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      name: transmission-ui
      port: 9091
      nodePort: {{ .Values.service.ports.ui }}
    - protocol: TCP
      name: transmission-tcp
      port: 51413
      nodePort: {{ .Values.service.ports.tcp }}
    - protocol: UDP
      name: transmission-udp
      port: 51413
      nodePort: {{ .Values.service.ports.udp }}
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
